
default: &default
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["REGION"] %>

development:
  <<: *default
  bucket_name: "flash-card-images-dev"

test:
  <<: *default
  database: "flash-card-images-test"

production:
  <<: *default
  bucket_name: "flash-card-images-prod"
